types:
    - mosquitto
    - paho
    - mqtt_node
    - mqtt_node_ws
    - cancel
templates:
    - template_mosquitto.yaml
    - template_paho.yaml
    - template_mqtt_node.yaml
    - template_mqtt_node_ws.yaml
    - cancel
